Repository unicef/inventory, pull requests merged in 2021-08, with the labels that each got.

#45 Add code syntax highlighting to code blocks #39
  config.toml
  content/meta/maintainers-guide.en.adoc
  syntax.css
Labels: T: new change

#50 l10n: Add base Spanish translations for Inventory
  config.toml
Labels: T: new change

#25 PR for #12 Highlight related articles at the bottom of each article.
  config.toml
  content/communities/fedora.en.adoc
  content/communities/public-lab.en.adoc
  content/data/milestone-roadmap.en.adoc
  content/data/model-card.en.adoc
  content/data/traps.en.adoc
  content/design/reading-list.en.adoc
  content/dev-tools/continuous-integration.en.adoc
  content/documentation/frontier-tech-tips.en.adoc
  content/documentation/hall-of-fame.en.adoc
  content/documentation/reading-list.en.adoc
  content/documentation/text-editors.en.adoc
  content/foss/_index.en.adoc
  content/foss/business-sustainability.adoc
  content/foss/contributor-license-agreement-cla.en.adoc
  content/foss/governance.adoc
  content/foss/gpl-comparison.en.adoc
  content/foss/reading-list-foss.en.adoc
  content/foss/reading-list-legal.en.adoc
  content/foss/reading-list-outreach.en.adoc
  content/hardware/case-studies.en.adoc
  content/hardware/documentation.en.adoc
  content/hardware/intro.en.adoc
  content/hardware/licensing.en.adoc
  content/hardware/projects.en.adoc
  content/hardware/reading-list.en.adoc
  content/meta/modules.en.adoc
  content/meta/needs-assessment-template.en.adoc
  content/meta/overview.en.adoc
  content/meta/templates.en.adoc
  content/meta/workflow-metrics.en.adoc
  content/meta/workplan-bridge-funding.en.adoc
  content/missions/codes-of-conduct.en.adoc
  content/missions/good-first-issue.en.adoc
  content/project-management/issue-templates.en.adoc
  content/project-management/project-boards.en.adoc
  content/project-management/reading-list.en.adoc
  content/reproducibility/_index.en.adoc
  content/reproducibility/reading-list.en.adoc
Labels: T: new change

#54 meta: Document how to create Inventory categories
  content/meta/create-new-category.en.adoc
  content/meta/maintainers-guide.en.adoc
  content/meta/modules.en.adoc
Labels: C: content, T: new change

#55 static: Show site favicon in browser tab/window
  config.toml
  content/meta/maintainers-guide.en.adoc
  content/project-management/issue-templates.en.adoc
  content/project-management/project-boards.en.adoc
  static/images/UN072995.jpg
  static/images/UNI309823.jpg
  static/images/banner.jpg
  static/images/favicon.png
  static/images/meta/ci-pipeline.png
  static/images/project-management/teleirc-bug-template-example.png
  static/images/project-management/teleirc-issue-templates.png
  static/images/project-management/teleirc-project-board.png
Labels: T: bug

#52 Create three new categories: Governance, Legal & Policy, Sustainability (closes #48)
  config.toml
  content/foss/_index.en.adoc
  content/foss/community.en.adoc
  content/foss/reading-list-outreach.en.adoc
  content/governance/_index.en.adoc
  content/governance/governance.en.adoc
  content/governance/reading-list.en.adoc
  content/legal-policy/_index.en.adoc
  content/legal-policy/contributor-license-agreement-cla.en.adoc
  content/legal-policy/gpl-comparison.en.adoc
  content/legal-policy/reading-list.en.adoc
  content/meta/overview.en.adoc
  content/project-management/reading-list.en.adoc
  content/sustainability/_index.en.adoc
  content/sustainability/business-sustainability.en.adoc
Labels: C: content, T: new change

#58 Add asciidoc config for automatic TOC
  config.toml
  content/dev-tools/continuous-integration.en.adoc
  content/governance/governance.en.adoc
  content/hardware/intro.en.adoc
  content/legal-policy/contributor-license-agreement-cla.en.adoc
  content/legal-policy/gpl-comparison.en.adoc
  content/meta/create-new-category.en.adoc
  content/meta/maintainers-guide.en.adoc
  content/meta/modules.en.adoc
  content/meta/workplan-bridge-funding.en.adoc
  content/missions/codes-of-conduct.en.adoc
  content/project-management/project-boards.en.adoc
Labels: T: improvement

#62 sustainability: Rewrite approaches page (closes #37)
  content/sustainability/approaches.en.adoc
  content/sustainability/business-sustainability.en.adoc
Labels: C: content, T: improvement

#64 missions: Create a template for writing new Missions
  content/meta/create-new-mission.en.adoc
  content/missions/_template.en.adoc
Labels: C: content, T: new change
